name: Build Image
on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Setup a local virtual environment
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      - uses: actions/cache@v3
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install the project dependencies
        run: poetry install
      - name: Active environment
        run: |
          source $(poetry env info --path)/bin/activate
          echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
          echo "PYTHONHOME=" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pack the model
        run: poetry run python -m gea.deployment.pack
      - uses: bentoml/build-bento-action@v1
        id: bento
        with:
          bentofile: 'gea/deployment/bentofile.yaml'
      - name: Build and push BentoContainer
        uses: bentoml/containerize-push-action@v1
        with:
          bento-tag: ${{ steps.bento.outputs.bento-tag }}
          push: true
          tags: fernandocamargoai/genetic_engineering_attribution_service:latest
      